config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import (mailing, mailing_logs, clients, MailingCreateView, mailing_info, MailingUpdateView,
                           MailingDeleteView, ClientCreateView, client_info, ClientUpdateView, ClientDeleteView, toggle_activity,
                           users, ban, blog)


app_name = 'mailing'

urlpatterns = [
    path('', mailing, name='mailings'),
    path('logs/', mailing_logs, name='mailing_logs'),
    path('clients/', clients, name='clients'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/<int:mailing_id>/', mailing_info, name='mailing_info'),
    path('mailing/edit/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/<int:client_id>/', client_info, name='client_info'),
    path('clients/edit/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
    path('users', users, name='users'),
    path('users/ban/<int:pk>', ban, name='ban'),
    path('blog/<int:pk>', blog, name='blog')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import  path
from django.views.generic import TemplateView

from users.views import RegisterView, EmailVerify, MyLoginView

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    email_verify = models.BooleanField(default=False)
    is_blocked = models.BooleanField(default=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm as DjangoAuthenticationForm
from django.core.exceptions import ValidationError
from users.utils import send_email
from users.models import User


class AuthenticationForm(DjangoAuthenticationForm):

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(
                self.request,
                email=email,
                password=password,
            )
            if not self.user_cache.email_verify:
                send_email(self.request, self.user_cache)
                raise ValidationError(
                    'Почта не подтверждена, пожалуйста, проверьте почтовый ящик',
                    code='invalid_login',
                )

            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

mailing/views.py
from smtplib import SMTPException

from apscheduler.jobstores.base import JobLookupError
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, UpdateView, DeleteView

from config.settings import CACHE_ENABLED
from users.models import User
from .models import Mailing, MailingLog, Client, Message, Blog
from apscheduler.schedulers.background import BackgroundScheduler
from django.conf import settings
from django.core.mail import send_mail
from apscheduler.triggers.cron import CronTrigger
from django_apscheduler.jobstores import DjangoJobStore
from mailing.models import Mailing, Message, Client
from django_apscheduler.models import DjangoJobExecution
import logging

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")


def my_job(object, body, clients, id):
    try:
        send_mail(object, body, settings.EMAIL_HOST_USER, [*clients])
        MailingLog.objects.create(status='Успешно', mailing_id=id)
    except SMTPException as e:
        MailingLog.objects.create(status='Неудача', response=e, mailing_id=id)


def delete_old_job_executions(max_age=604_800):
  DjangoJobExecution.objects.delete_old_job_executions(max_age)


@login_required
def mailing(request):
    logger = logging.getLogger(__name__)
    mails = Mailing.objects.filter(user_id=request.user.pk)
    messages = Message.objects.all()
    for m in mails:
        msg = messages.get(mailing_id=m.id)
        clients = Client.objects.filter(mailing__id=m.id).values_list('email', flat=True)
        if m.interval == 'Раз в день' and m.status == 'Запущена':
            scheduler.add_job(
                my_job,
                trigger=CronTrigger(hour=m.time.hour, minute=m.time.minute, second=m.time.second),
                id=f"my_job{m.id}",
                max_instances=1,
                replace_existing=True,
                args=[msg.message_object, msg.message_body, clients, m.id],
            )
        elif m.interval == 'Раз в неделю' and m.status == 'Запущена':
            scheduler.add_job(
                my_job,
                trigger=CronTrigger(day_of_week=0, hour=m.time.hour, minute=m.time.minute, second=m.time.second),
                id=f"my_job{m.id}",
                max_instances=1,
                replace_existing=True,
                args=[msg.message_object, msg.message_body, clients, m.id],
            )
        elif m.interval == 'Раз в месяц' and m.status == 'Запущена':
            scheduler.add_job(
                my_job,
                trigger=CronTrigger(day=1, hour=m.time.hour, minute=m.time.minute, second=m.time.second),
                id=f"my_job{m.id}",
                max_instances=1,
                replace_existing=True,
                args=[msg.message_object, msg.message_body, clients, m.id],
            )

    logger.info("Added job 'my_job'.")

    scheduler.add_job(
        delete_old_job_executions,
        trigger=CronTrigger(
            day_of_week="mon", hour="00", minute="00"
        ),
        id="delete_old_job_executions",
        max_instances=1,
        replace_existing=True,
    )
    logger.info(
        "Added weekly job: 'delete_old_job_executions'."
    )

    try:
        if not scheduler.running:
            logger.info("Starting scheduler...")
            scheduler.start()
    except KeyboardInterrupt:
        logger.info("Stopping scheduler...")
        scheduler.shutdown()
        logger.info("Scheduler shut down successfully!")
    if request.user.is_staff and request.user.groups.filter(name='manager').exists():
        if CACHE_ENABLED:
            key = f'mailing_info'
            mailing_info = cache.get(key)
            if mailing_info is None:
                mailing_info = Mailing.objects.order_by('id')
                cache.set(key, mailing_info)
            else:
                mailing_info = Mailing.objects.order_by('id')
    else:
        if CACHE_ENABLED:
            key = f'mailing_info'
            mailing_info = cache.get(key)
            if mailing_info is None:
                mailing_info = Mailing.objects.filter(user_id=request.user.pk).order_by('id')
                cache.set(key, mailing_info)
            else:
                mailing_info = Mailing.objects.filter(user_id=request.user.pk).order_by('id')
    is_manager = request.user.is_staff and request.user.groups.filter(name='manager').exists()
    active_count = len(mailing_info.filter(status='Запущена'))
    blog = Blog.objects.order_by('?')[:3]
    clients_count = len(Client.objects.all())
    return render(request, 'mailings.html', context={"mailing": mailing_info, "is_manager": is_manager, "blogs": blog, "mailing_count": len(mailing_info), "active_count": active_count, "client_count": clients_count})

@login_required
def mailing_logs(request):
    logs = []
    if request.user.is_staff and request.user.groups.filter(name='manager').exists():
        logs = MailingLog.objects.all()
    else:
        mailing = Mailing.objects.filter(user_id=request.user.pk)
        for m in mailing:
            logs = MailingLog.objects.filter(mailing_id=m.id)
    is_manager = request.user.is_staff and request.user.groups.filter(name='manager').exists()
    return render(request, 'mailing_logs.html', context={"mailing_log": logs, "is_manager": is_manager})

@login_required
def clients(request):
    if request.user.is_staff and request.user.groups.filter(name='manager').exists():
        clients_list = Client.objects.all()
    else:
        clients_list = Client.objects.filter(user_id=request.user.pk)
    is_manager = request.user.is_staff and request.user.groups.filter(name='manager').exists()
    return render(request, 'clients.html', context={"clients_list": clients_list, "is_manager": is_manager})


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    fields = ('clients', 'time', 'interval')
    success_url = reverse_lazy('mailing:mailings')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.pk
        self.object.save()
        msg = Message()
        msg.mailing_id = self.object.id
        msg.message_object = self.request.POST.get('object')
        msg.message_body = self.request.POST.get('message')
        msg.save()
        return super().form_valid(form)

@login_required
def mailing_info(request, mailing_id):
    is_manager = request.user.is_staff and request.user.groups.filter(name='manager').exists()
    mailing_info = Mailing.objects.get(id=mailing_id)
    msg = Message.objects.get(mailing_id=mailing_id)
    return render(request, 'mailing.html', context={"mailing": mailing_info, "msg": msg, "is_manager": is_manager})


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    fields = ('clients', 'time', 'interval')
    success_url = reverse_lazy('mailing:mailings')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        msg = Message.objects.get(mailing_id=self.kwargs['pk'])
        msg.message_object = self.request.POST.get('object')
        msg.message_body = self.request.POST.get('message')
        msg.save()
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailings')

    def form_valid(self, form):
        try:
            scheduler.remove_job(f'my_job{self.kwargs["pk"]}')
        except JobLookupError:
            pass
        return super().form_valid(form)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('fio', 'email', 'comment')
    success_url = reverse_lazy('mailing:clients')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.pk
        self.object.save()
        return super().form_valid(form)

@login_required
def client_info(request, client_id):
    client = Client.objects.all()
    client_info = client.get(id=client_id)
    is_manager = request.user.is_staff and request.user.groups.filter(name='manager').exists()
    return render(request, 'client.html', context={"client": client_info, "is_manager": is_manager})


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('fio', 'email', 'comment')
    success_url = reverse_lazy('mailing:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients')

@login_required
def toggle_activity(request, pk):
    mailing = Mailing.objects.get(id=pk)
    if mailing.status == 'Создана' or mailing.status == 'Завершена':
        scheduler.wakeup()
        mailing.status = 'Запущена'
        mailing.save()
    elif mailing.status == 'Запущена':
        scheduler.pause_job(f'my_job{pk}')
        mailing.status = 'Завершена'
        mailing.save()
    return redirect(reverse('mailing:mailings'))


@permission_required('users.change_user')
@login_required
def users(request):
    usrs = User.objects.all().order_by('id')
    if request.user.is_blocked:
        return render(request, 'is_blocked.html')
    return render(request, 'users.html', context={"usrs": usrs})


@permission_required('users.change_user')
@login_required
def ban(request, pk):
    user = User.objects.get(id=pk)
    if user.is_blocked:
        user.is_blocked = False
        user.save()
    elif not user.is_blocked:
        user.is_blocked = True
        user.save()
    return redirect(reverse('mailing:users'))


@cache_page(60)
def blog(request, pk):
    blog = Blog.objects.get(id=pk)
    blog.watch = blog.watch + 1
    blog.save()

users/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView
from django.core.exceptions import ValidationError
from users.forms import UserRegisterForm, AuthenticationForm
from users.models import User
from users.utils import send_email
from django.contrib.auth.tokens import default_token_generator as token_generator


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'



    def post(self, request, *args, **kwargs):
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email(request, user)
            return redirect('users:confirm_email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class MyLoginView(LoginView):
    form_class = AuthenticationForm


class EmailVerify(View):
    User = get_user_model()

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('mailing:mailings')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (
                TypeError,
                ValueError,
                OverflowError,
                User.DoesNotExist,
                ValidationError,
        ):
            user = None
        return user

mailing/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылки</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% if user.is_blocked and not user.is_anonymous %}
<h5 class="my-0 mr-md-auto font-weight-normal">Ваш аккаунт заблокирован. Пожалуйста, обратитесь к менеджеру.</h5>
{% else %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис рассылки</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailings' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:clients' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailing_logs' %}">Логи</a>
        {% if is_manager %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:users' %}">Пользователи</a>
        {% else %}
        {% endif %}
    </nav>
    {% if user.is_authenticated %}
    <a class="ms-auto btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
    <div class="ms-auto">
    <a class="btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
    <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
    </div>
    {% endif %}
</div>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
<h6 class="my-0 mr-md-auto font-weight-normal">Интересные статьи:</h6><br>
{% for b in blogs %}
<a class="p-2 btn btn-outline-primary ms-4" href="blog/{{ b.id }}">{{ b.title }}</a>
{% endfor %}
</div>
{% block content %}
{% endblock %}
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/blog.html
{% extends "base.html" %}
{% block content %}

<div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="my-0 mr-md-auto font-weight-normal">{{ blog.title }}</h5><br><br>
                        <img src="/media/{{ blog.image }}"><br><br>
                        <p>{{ blog.body }}</p><br><br>
                        <p>Статья опубликована {{ blog.public_date }}</p><br><br>
                        <p>Просмотрело: {{ blog.watch }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/client.html
{% extends "base.html" %}
{% block content %}

<div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                            ФИО: {{ client.fio }}<br><br>
                            Почта: {{ client.email }}<br><br>
                            Комментарий: {{ client.comment }}<br><br>
                            {% if is_manager %}
                            {% else %}
                                <a type="button" href="{% url 'mailing:update_client' client.id %}" class="btn btn-primary">Редактировать</a>
                                <a type="button" href="{% url 'mailing:delete_client' client.id %}" class="btn btn-danger">Удалить</a>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/clients.html
{% extends "base.html" %}
{% block content %}

{% if is_manager %}
{% else %}
    <a class="p-2 btn btn-primary ms-4" href="{% url 'mailing:create_client' %}">Добавить пользователя</a>
{% endif %}

<ul class="list-group list-group-flush">
<li class="list-group-item text-center"><div class="row fw-bold g-0"><div class="col">ФИО</div><div class="col">Почта</div><div class="col">Комментарий</div></div></li>
{% for cl in clients_list %}
    <li class="list-group-item text-center"><a href="/clients/{{ cl.id }}" class="row btn p-0 list-group-item-action d-flex g-0"><div class="col">{{cl.fio}}</div><div class="col">{{cl.email}}</div><div class="col">{{cl.comment}}</div></a></li>
{% endfor %}
</ul>
{% endblock %}

mailing/templates/is_blocked.html
<h5 class="my-0 mr-md-auto font-weight-normal">Ваш аккаунт заблокирован. Пожалуйста, обратитесь к менеджеру.</h5>

mailing/templates/mailing.html
{% extends "base.html" %}
{% block content %}

<div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                            Время отправки: {{ mailing.time }}<br><br>
                            Периодичность: {{ mailing.interval }}<br><br>
                            Статус: {{ mailing.status }}<br><br>
                            Тема письма: {{ msg.message_object }}<br><br>
                            Тело письма: {{ msg.message_body }}<br><br>
                        {% if is_manager %}
                        {% else %}
                            <a type="button" href="{% url 'mailing:update_mailing' mailing.id %}" class="btn btn-primary">Редактировать</a>
                            <a type="button" href="{% url 'mailing:delete_mailing' mailing.id %}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing_logs.html
{% extends "base.html" %}
{% block content %}

<ul class="list-group list-group-flush">
<li class="list-group-item text-center"><div class="row fw-bold g-0"><div class="col">Дата и время последней попытки</div><div class="col">Статус</div><div class="col">Ответ сервера</div></div></li>
{% for mg in mailing_log %}
    <li class="list-group-item text-center"><a href="/mailing/{{ mg.mailing_id }}" class="row btn p-0 list-group-item-action d-flex g-0"><div class="col">{{mg.mailing_datetime}}</div><div class="col">{{mg.status}}</div><div class="col">{{mg.response}}</div></a></li>
{% endfor %}
</ul>
{% endblock %}

mailing/templates/mailings.html
{% extends "base.html" %}
{% block content %}

{% if is_manager %}
{% else %}
<a class="p-2 btn btn-primary ms-4" href="{% url 'mailing:create_mailing' %}">Создать рассылку</a> <p class="ms-4">Кол-во рассылок:{{ mailing_count }} </p> <p class="ms-4">Кол-во активных рассылок:{{ active_count }}</p><p class="ms-4">Кол-во клиентов:{{ client_count }}</p>
{% endif %}

<ul class="list-group list-group-flush">
<li class="list-group-item text-center"><div class="row fw-bold g-0"><div class="col">Время</div><div class="col">Периодичность</div><div class="col">Статус</div></div></li>
{% for m in mailing %}
<li class="list-group-item text-center"><a href="/mailing/{{ m.id }}" class="row btn p-0 list-group-item-action d-flex g-0"><div class="col">{{m.time}}</div> <div class="col">{{m.interval}}</div> <div class="col">{{m.status}}</div>{% if m.status == 'Создана' %}<a href="{% url 'mailing:toggle_activity' m.id %}" class="btn btn-success">Запустить</a>{% elif m.status == 'Завершена' %}<a href="{% url 'mailing:toggle_activity' m.id %}" class="btn btn-success">Запустить</a>{% elif m.status == 'Запущена' %}<a href="{% url 'mailing:toggle_activity' m.id %}" class="btn btn-danger">Завершить</a>{% endif %}</a></li>
{% endfor %}
</ul>
{% endblock %}

mailing/templates/users.html
{% extends "base.html" %}
{% block content %}

<ul class="list-group list-group-flush">
<li class="list-group-item text-center"><div class="row fw-bold g-0"><div class="col">id</div><div class="col">email</div><div class="col">Статус блокировки</div></div></li>
{% for u in usrs %}
<li class="list-group-item text-center"><a href="users/ban/{{ u.id }}" class="row btn p-0 list-group-item-action d-flex g-0"><div class="col">{{u.id}}</div> <div class="col">{{u.email}}</div> <div class="col">{{u.is_blocked}}</div></a></li>
{% endfor %}
</ul>
{% endblock %}