config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import (mailing, mailing_logs, clients, MailingCreateView, mailing_info, MailingUpdateView,
                           MailingDeleteView, ClientCreateView, client_info, ClientUpdateView, ClientDeleteView, toggle_activity,
                           users, ban, blog)


app_name = 'mailing'

urlpatterns = [
    path('', mailing, name='mailings'),
    path('logs/', mailing_logs, name='mailing_logs'),
    path('clients/', clients, name='clients'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/<int:mailing_id>/', mailing_info, name='mailing_info'),
    path('mailing/edit/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/<int:client_id>/', client_info, name='client_info'),
    path('clients/edit/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
    path('users', users, name='users'),
    path('users/ban/<int:pk>', ban, name='ban'),
    path('blog/<int:pk>', blog, name='blog')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import  path
from django.views.generic import TemplateView

from users.views import RegisterView, EmailVerify, MyLoginView

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    email_verify = models.BooleanField(default=False)
    is_blocked = models.BooleanField(default=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm as DjangoAuthenticationForm
from django.core.exceptions import ValidationError
from users.utils import send_email
from users.models import User


class AuthenticationForm(DjangoAuthenticationForm):

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(
                self.request,
                email=email,
                password=password,
            )
            if not self.user_cache.email_verify:
                send_email(self.request, self.user_cache)
                raise ValidationError(
                    'Почта не подтверждена, пожалуйста, проверьте почтовый ящик',
                    code='invalid_login',
                )

            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

users/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView
from django.core.exceptions import ValidationError
from users.forms import UserRegisterForm, AuthenticationForm
from users.models import User
from users.utils import send_email
from django.contrib.auth.tokens import default_token_generator as token_generator


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'



    def post(self, request, *args, **kwargs):
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email(request, user)
            return redirect('users:confirm_email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class MyLoginView(LoginView):
    form_class = AuthenticationForm


class EmailVerify(View):
    User = get_user_model()

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('mailing:mailings')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (
                TypeError,
                ValueError,
                OverflowError,
                User.DoesNotExist,
                ValidationError,
        ):
            user = None
        return user

users/templates/users/confirm.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                            <p>Пожалуйста, подтвердите email, перейдя на почту</p>
                            <a type="button" href="{% url 'mailing:mailings' %}" class="btn btn-primary">Вернуться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/invalid_verify.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                            <p>Срок Вашей ссылки истёк, попробуйте снова</p>
                            <a type="button" href="{% url 'users:login' %}" class="btn btn-primary">Вернуться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}<br>
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}<br>
                            <button type="submit" class="btn btn-primary">Регистрация</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verify.html
{% autoescape off %}

Пожалуйста, перейдите по ссылке, чтобы закончить регистрацию:
http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}


{% endautoescape %}